# Usar una imagen base de Python 3.11
FROM python:3.11-slim

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el archivo de dependencias al contenedor
COPY requirements.txt .

# Instalar las dependencias del archivo requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el resto de los archivos de la aplicación al contenedor
COPY . .

# Exponer el puerto que usa la aplicación (Render configurará la variable PORT)
EXPOSE 8050

# Comando para ejecutar la aplicación (reemplaza con waitress si prefieres)
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:$PORT", "dashboard:server"]
